table DIM_CountryMarket
	lineageTag: 5314d05c-7699-41f2-8999-a73cf9a30cf9

	column CountryID
		dataType: string
		lineageTag: 89cdb547-b887-4292-858d-82cfa3baab0f
		summarizeBy: none
		sourceColumn: CountryID

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		lineageTag: be432323-89a7-4099-90c3-50b0e216c252
		summarizeBy: none
		sourceColumn: CountryName

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 89c58de8-1caf-4c67-8b66-5093c1aa26f6
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	partition DIM_CountryMarket = m
		mode: import
		source =
				let
				    Source = Sql.Databases("LAPTOP-CPPC75DP\SQLEXPRESS"),
				    Super_Store = Source{[Name="Super_Store"]}[Data],
				    dbo_DIM_CountryMarket = Super_Store{[Schema="dbo",Item="DIM_CountryMarket"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dbo_DIM_CountryMarket,"Democratic Republic of the Congo","DR Congo",Replacer.ReplaceText,{"CountryName"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Dominican Republic","Dom. Republic",Replacer.ReplaceText,{"CountryName"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

