DEFINE
	MEASURE
		'Calculations'[ProfitMarginLvl] =
		SWITCH(
			TRUE(),
			[ProfitMargin] < 0.05, "Low",
			[ProfitMargin] < 0.15, "Moderate",
			[ProfitMargin] >= 0.15, "Excellent"
		)
EVALUATE
	SUMMARIZECOLUMNS(
		"ProfitMargin2014", [ProfitMargin],
		"Level", [ProfitMarginLvl])