DEFINE
	MEASURE 'Calculations'[CY_ConsumerSales] =
		FORMAT(
			CALCULATE(
				[CYSales],
				'DIM_Segment'[Segment] = "Consumer"
			),
			"$#"
		)
EVALUATE
	SUMMARIZECOLUMNS(
		"CY_ConsumerSales", [CY_ConsumerSales]
	)