DEFINE
	MEASURE 'Calculations'[CY_ConsumerSales] =
		CALCULATE(
			[CYSales],
			'DIM_Segment'[Segment] = "Consumer"
		)

	MEASURE 'Calculations'[ConsumerSalesPrc] =

		VAR PrevYrConsumerSales =
		CALCULATE(
			[PrevYrSales],
			'DIM_Segment'[Segment] = "Consumer"
		)

		VAR _ConsumerSalesPrc =
		DIVIDE(
			[CY_ConsumerSales] - PrevYrConsumerSales,
			PrevYrConsumerSales
		)

		RETURN

			FORMAT(
				_ConsumerSalesPrc,
				"▲ +0.00%; ▼-0.00%"
			)

	MEASURE 'Calculations'[CY_CorporateSales] =
		CALCULATE(
			[CYSales],
			'DIM_Segment'[Segment] = "Corporate"
		)

	MEASURE 'Calculations'[CorporateSalesPrc] =

		VAR PrevYrCorporateSales =
		CALCULATE(
			[PrevYrSales],
			'DIM_Segment'[Segment] = "Corporate"
		)

		VAR _CorporateSalesPrc =
		DIVIDE(
			[CY_CorporateSales] - PrevYrCorporateSales,
			PrevYrCorporateSales
		)

		RETURN

			FORMAT(
				_CorporateSalesPrc,
				"▲ +0.00%; ▼-0.00%"
			)

	MEASURE 'Calculations'[CY_HomeOfficeSales] =
		CALCULATE(
			[CYSales],
			'DIM_Segment'[Segment] = "Home Office"
		)

	MEASURE 'Calculations'[HomeOfficeSalesPrc] =

		VAR PrevYrHomeOfficeSales =
		CALCULATE(
			[PrevYrSales],
			'DIM_Segment'[Segment] = "Home Office"
		)

		VAR _HomeOfficeSalesPrc =
		DIVIDE(
			[CY_HomeOfficeSales] - PrevYrHomeOfficeSales,
			PrevYrHomeOfficeSales
		)

		RETURN

			FORMAT(
				_HomeOfficeSalesPrc,
				"▲ +0.00%; ▼-0.00%"
			)


EVALUATE
	SUMMARIZECOLUMNS(
		"ConsumerSales", FORMAT(
			[CY_ConsumerSales],
			"#,00"
		),
		"ConsumerSalesPrc", [ConsumerSalesPrc],

		"CorporateSales", FORMAT(
			[CY_CorporateSales],
			"#,00"
		),
		"CorporateSalesPrc", [CorporateSalesPrc],

		"HomeOfficeSales", FORMAT(
			[CY_HomeOfficeSales],
			"#,00"
		),
		"HomeOfficeSalesPrc", [HomeOfficeSalesPrc]
	)